language: rust
sudo: false
matrix:
  include:
    - rust: nightly
script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
after_success: |
    [ "$TRAVIS_RUST_VERSION" = nightly ] &&
    [ "$TRAVIS_BRANCH" = master ] &&
    [ "$TRAVIS_PULL_REQUEST" = false ] &&
    bash deploy-docs.sh
notifications:
    webhooks: http://huon.me:54857/travis
